<?php
//
// SIMP
// Descricao: lista de linguas
// Autor: Rubens Takiguti Ribeiro
// Orgao: TecnoLivre - Cooperativa de Tecnologia e Solucoes Livres
// E-mail: rubens@tecnolivre.com.br
// Versao: 1.0.0.0
// Data: 10/01/2011
// Modificado: 10/01/2011
// Copyright (C) 2011  Rubens Takiguti Ribeiro
// License: LICENSE.TXT
//
$vetor = array(
    'af'    => 'Afrikaans',
    'sq'    => 'Albanian',
    'ar'    => 'Arabic',
    'ar-dz' => 'Arabic (Algeria)',
    'ar-bh' => 'Arabic (Bahrain)',
    'ar-eg' => 'Arabic (Egypt)',
    'ar-jo' => 'Arabic (Jordan)',
    'ar-kw' => 'Arabic (Kuwait)',
    'ar-lb' => 'Arabic (Lebanon)',
    'ar-ma' => 'Arabic (Morocco)',
    'ar-om' => 'Arabic (Oman)',
    'ar-qa' => 'Arabic (Qatar)',
    'ar-sa' => 'Arabic (Saudi Arabia)',
    'ar-tn' => 'Arabic (Tunisia)',
    'ar-ae' => 'Arabic (U.A.E.)',
    'ar-ye' => 'Arabic (Yemen)',
    'hy'    => 'Armenian',
    'as'    => 'Assamese',
    'az'    => 'Azeri',
    'eu'    => 'Basque',
    'be'    => 'Belarusian',
    'bn'    => 'Bengali',
    'bg'    => 'Bulgarian',
    'ca'    => 'Catalan',
    'zh'    => 'Chinese',
    'zh-cn' => 'Chinese (China)',
    'zh-hk' => 'Chinese (Hong Kong SAR)',
    'zh-mo' => 'Chinese (Macau SAR)',
    'zh-sg' => 'Chinese (Singapore)',
    'zh-tw' => 'Chinese (Taiwan)',
    'hr'    => 'Croatian',
    'cs'    => 'Czech',
    'da'    => 'Danish',
    'nl-be' => 'Dutch (Belgium)',
    'nl'    => 'Dutch (Netherlands)',
    'en'    => 'English',
    'en-au' => 'English (Australia)',
    'en-bz' => 'English (Belize)',
    'en-ca' => 'English (Canada)',
    'en-ie' => 'English (Ireland)',
    'en-jm' => 'English (Jamaica)',
    'en-nz' => 'English (New Zealand)',
    'en-ph' => 'English (Philippines)',
    'en-za' => 'English (South Africa)',
    'en-tt' => 'English (Trinidad)',
    'en-gb' => 'English (United Kingdom)',
    'en-us' => 'English (United States)',
    'en-zw' => 'English (Zimbabwe)',
    'et'    => 'Estonian',
    'fo'    => 'Faeroese',
    'fa'    => 'Farsi',
    'fi'    => 'Finnish',
    'fr-be' => 'French (Belgium)',
    'fr-ca' => 'French (Canada)',
    'fr'    => 'French (France)',
    'fr-lu' => 'French (Luxembourg)',
    'fr-mc' => 'French (Monaco)',
    'fr-ch' => 'French (Switzerland)',
    'mk'    => 'FYRO Macedonian',
    'ka'    => 'Georgian',
    'de-at' => 'German (Austria)',
    'de'    => 'German (Germany)',
    'de-li' => 'German (Liechtenstein)',
    'de-lu' => 'German (Luxembourg)',
    'de-ch' => 'German (Switzerland)',
    'el'    => 'Greek',
    'gu'    => 'Gujarati',
    'he'    => 'Hebrew',
    'hi'    => 'Hindi',
    'hu'    => 'Hungarian',
    'is'    => 'Icelandic',
    'id'    => 'Indonesian',
    'it'    => 'Italian (Italy)',
    'it-ch' => 'Italian (Switzerland)',
    'ja'    => 'Japanese',
    'kn'    => 'Kannada',
    'kk'    => 'Kazakh',
    'ko'    => 'Korean',
    'lv'    => 'Latvian',
    'lt'    => 'Lithuanian',
    'ms'    => 'Malay',
    'ml'    => 'Malayalam',
    'mr'    => 'Marathi',
    'ne'    => 'Nepali (India)',
    'no'    => 'Norwegian',
    'nb-no' => 'Norwegian (Bokmal)',
    'nn-no' => 'Norweigan (Nynorsk)',
    'or'    => 'Oriya',
    'pl'    => 'Polish',
    'pt-br' => 'Portuguese (Brazil)',
    'pt'    => 'Portuguese (Portugal)',
    'pa'    => 'Punjabi',
    'ro'    => 'Romanian',
    'ru'    => 'Russian',
    'sa'    => 'Sanskrit',
    'sr'    => 'Serbian',
    'sk'    => 'Slovak',
    'sl'    => 'Slovenian',
    'es'    => 'Spanish',
    'es-ar' => 'Spanish (Argentina)',
    'es-bo' => 'Spanish (Bolivia)',
    'es-cl' => 'Spanish (Chile)',
    'es-co' => 'Spanish (Colombia)',
    'es-cr' => 'Spanish (Costa Rica)',
    'es-do' => 'Spanish (Dominican Republic)',
    'es-ec' => 'Spanish (Ecuador)',
    'es-sv' => 'Spanish (El Salvador)',
    'es-gt' => 'Spanish (Guatemala)',
    'es-hn' => 'Spanish (Honduras)',
    'es-mx' => 'Spanish (Mexico)',
    'es-ni' => 'Spanish (Nicaragua)',
    'es-pa' => 'Spanish (Panama)',
    'es-py' => 'Spanish (Paraguay)',
    'es-pe' => 'Spanish (Peru)',
    'es-pr' => 'Spanish (Puerto Rico)',
    'es-uy' => 'Spanish (Uruguay)',
    'es-ve' => 'Spanish (Venezuela)',
    'sw'    => 'Swahili',
    'sv'    => 'Swedish',
    'sv-fi' => 'Swedish (Finland)',
    'ta'    => 'Tamil',
    'tt'    => 'Tatar',
    'te'    => 'Telugu',
    'th'    => 'Thai',
    'tr'    => 'Turkish',
    'uk'    => 'Ukrainian',
    'ur'    => 'Urdu',
    'uz'    => 'Uzbek',
    'vi'    => 'Vietnamese'
);